<?php

/**
 * @file
 * Main code for N1ED module.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function n1ed_plugin() {
  return array(
    'n1ed' => array(
      'name' => 'N1ED',
      'desc' => t('N1ED. See <a href=":addon_page_url">@addon_page_title</a> for more details.',
        array(
          ':addon_page_url' => 'https://n1ed.com',
          '@addon_page_title' => t('addon page'),
        )),
      'path' => base_path() . 'libraries/N1ED'
    ),
  );
}

function n1ed_editor_js_settings_alter(array &$settings) {
    foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
        if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
            $settings['editor']['formats'][$text_format_id]['editorSettings']['skin'] = 'n1theme,/' . drupal_get_path('module', 'n1ed') . "/js/skin/n1theme/";
        }
    }
}
