<?php

use Drupal\Core\Config\Entity\ConfigEntityType;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_update_N().
 */
function profile_update_8701()
{
    $definition_update_manager = \Drupal::entityDefinitionUpdateManager();
    $entity_type = $definition_update_manager->getEntityType('profile');
    $keys = $entity_type->getKeys();
    var_dump($keys);
    die;
    $keys['published'] = 'status';
    $entity_type->set('entity_keys', $keys);
    $definition_update_manager->updateEntityType($entity_type);
}
