<?php

/**
 * @file
 * Main code for BootstrapEditor module.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function bootstrap_editor_plugin() {
  return array(
    'bootstrap_editor' => array(
      'name' => 'BootstrapEditor',
      'desc' => t('N1ED. See <a href=":addon_page_url">@addon_page_title</a> for more details.',
        array(
          ':addon_page_url' => 'https://n1ed.com',
          '@addon_page_title' => t('addon page'),
        )),
      'path' => base_path() . 'libraries/BootstrapEditor'
    ),
  );
}
